feriavirtual/feriavirtual2/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feriavirtualapp.urls')),
]

feriavirtual/feriavirtualapp/urls.py
from django.urls import path , include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from .views import *




urlpatterns = [

    path('ComprobantePDF/<int:pk>/', views.ComprobantePDF, name='ComprobantePDF'),

    
    path('lista-contratos/', views.listaContratos, name='listaContratos'),
    path('gestion-contratos/', views.gestionContratos, name='gestionContratos'),
    path('contratos/', views.contratos, name='contratos'),
    path('register/', views.register, name='register'),
    path('registerinterno/', views.registerinterno, name='register-interno'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('', views.index, name='index'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    
    path('pagar/<int:total>/<int:pk>', views.pagar, name="pagar"),
 
    path('seguimiento/<int:pk>/', views.seguimiento, name="seguimiento"),
    path('seguimientoLista/', views.seguimientoLista, name='seguimientoLista'),
    path('seguimientoDetalle/<int:pk>/', views.seguimientoDetalle, name='seguimientoDetalle'),
    path('Consulta/', views.Consulta, name='Consulta'),
    path('comprobante/<int:pk>/', views.comprobante, name='comprobante'),
    path('seguimientoComprobante/', views.seguimientoComprobante, name='seguimientoComprobante'),
    
    path('ingresar-productos/', views.ingresarproductos, name='ingresar-productos'),
    path('mis-productos/', views.misproductos, name='mis-productos'),
    
    
    path('venta/', views.venta, name='venta'),
    
    #path('subasta/<int:pk>/', views.subasta, name='subasta'),
    
    #path('pagarsubasta/<int:pk>/', views.pagarsubasta, name='pagarsubasta'),
    path('terminar/<int:pk>/', views.terminar, name='terminar'),
    path('terminarsaldo/', views.webpaycommit, name='terminarsaldo'),
    #path('pagar/<int:total>/<int:pk>', views.pagar, name='pagar'),
    path('pagar/', views.pagar, name='pagar'),
    
    path('Solicitud/', views.Solicitud, name='Solicitud'),
    path('Solicitudes/', views.solicitudes, name='Solicitudes'),
    path('modificarsoli/<int:pk>/', views.modificarSolicitud, name="modificarSolicitud"),

    path('registrarTransporte/', views.registrarTransporte, name="registrarTransporte"),
    path('transportesRegistrados/', views.transportesRegistrados, name="transportesRegistrados"),

    path('Venta-local/', views.Ventalocal, name="Ventalocal"),
    
    
    path('add_product_carrito/<int:product_id>/', add_product_carrito, name='add_product_carrito'),
    path('add_product_catalogo/<int:product_id>/', add_product_catalogo, name='add_product_catalogo'),
    path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
    path('carrito.html', views.webpay),

    path('solicitudClientes/', views.solicitudClientes, name="solicitudClientes"),

    path('solicitudesTransportista/', views.solicitudesTransportista, name="solicitudesTransportista"),
    path('modificarSolicitudTransportista/<int:pk>/', views.modificarSolicitudTransportista, name="modificarSolicitudTransportista"),

    path('solicitudesRevisor/', views.solicitudesRevisor, name="solicitudesRevisor"),
    path('modificarSolicitudRevisor/<int:pk>/', views.modificarSolicitudRevisor, name="modificarSolicitudRevisor"),

    path('solicitudesProductor/', views.solicitudesProductor, name="solicitudesProductor"),
    path('modificarsolicitudProductor/<int:pk>/', views.modificarSolicitudProductor, name="modificarsolicitudProductor"),

    path('solicitudesClienteExterno/', views.solicitudesClienteExterno, name="solicitudesClienteExterno"),
    path('modificarSolicitudClienteExterno/<int:pk>/', views.modificarSolicitudClienteExterno, name="modificarSolicitudClienteExterno"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feriavirtual/feriavirtualapp/models.py
from email.policy import default
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import fields
from django.db.models.fields import related
from django.utils import timezone
PRODUCTOS =(
    ("1", "Cerezas "),
    ("2", "Uvas"),
    ("3", "Arándanos "),
    ("4", "Nueces"),
    ("5", "Manzana"),
    ("6", "Ciruela"),
    ("7", "Peras"),
    ("9", "Durazno"),
    ("11", "Frutilla"),
    ("12", "Granada"),
    ("13", "Limón"),
    ("14", "Mandarina"),
    ("15", "Naranja"),
    ("16", "Sandia "),
    ("17", "Melón"),
    ("18", "Mora"),
    ("19", "Pera"),
    ("20", "Manzana"),
    )
#ATENDIENDO TAMAÑO Y CALIBRE LA FRUTA SE PUEDE CALIFICAR EN:
CALIBRE =(
    ("1", "Segunda"),
    ("2", "Primera"),
    ("3", "Extra "),
)
TAMAÑO =(
    ("1", "Liviano "),
    ("2", "Mediano"),
    ("3", "Pesado"),
)
EstadoSolicitudCompra =(
    ("1", "Aprobado"),
    ("2", "Rechazado"),
    ("3", "Pendiente"),
    ("4", "Subasta de transporte"),
    ("5", "Transporte Listo"),
    ("6","Entregado en bodega"),
    ("7","Viaje interrumpido (productor)"),
    ("8", "Revision de calidad"),
    ("9", "Rechazado en revision"),
    ("10", "Revisado"),
    ("11", "En camino"),
    ("12", "Viaje interrumpido (transportista)"),
    ("13", "Destino"),
    ("14", "Aceptado por el destinatario"),
    ("15", "Rechazado por el destinatario"),
    ("16", "Saldo"),
    ("17", "Completado")


    
    )
class User(AbstractUser):
    ROLES =(
    ("1", "Productor"),
    ("2", "Cliente externo"),
    ("3", "Cliente interno"),
    ("4", "Transportista"),
    ("5", "Consultor"),
    ("6", "Administrador"),
    ("7", "Revisor de calidad"),
    )
    dni = models.CharField(max_length=30,null=True)
    rol = models.CharField(max_length=50, choices = ROLES, null=True)
    imagen = models.ImageField(upload_to="Perfil",default='Perfil/default.png')
    direccion=models.CharField(max_length=50, null=True)
    codigopostal=models.IntegerField(default=0, null=True)
    disponible= models.BooleanField(default=True)
    def __str__(self):
        return f'{self.username}'
    



class Producto(models.Model):
    
    autor = models.ForeignKey(User, on_delete=models.CASCADE,related_name='producto')
    producto = models.CharField(max_length=50, choices = PRODUCTOS, null=True)
    variedad = models.CharField(max_length=50, null=True)
    calibre = models.CharField(max_length=50,choices = CALIBRE, null=True)
    cantidad = models.IntegerField(default=0)
    fecha_subida = models.DateTimeField(default=timezone.now)
    imagen = models.ImageField(upload_to="Productos", null=True)
    precio = models.IntegerField(default=0)
    Saldo= models.BooleanField(default=False)
    class Meta:
        ordering = ['-cantidad']

class Contrato(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_inicio = models.DateField(default=timezone.now)
    fecha_termino = models.DateField(default=timezone.now)
    vigencia = models.BooleanField(default=False)

class Transporte(models.Model):
    transportista = models.ForeignKey(User, on_delete=models.CASCADE)
    tamaño = models.CharField(max_length=50, choices = TAMAÑO, null=True)
    refrigeracion = models.BooleanField(default=False)
    tarifa = models.IntegerField(default=0)
    
    def __str__(self):
        return f'{self.transportista.username}: tamaño: {self.tamaño}: Refrigeracion: {self.refrigeracion}: Tarifa: {self.tarifa}'

    

class Post(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ManyToManyField(Producto, through='Post_productos',related_name="Postproducto")
    productoreq = models.CharField(max_length=50,choices=PRODUCTOS, null=True)
    #productor = models.ManyToManyField(User,related_name="productor" )
    #productor2 = models.ForeignKey(User, on_delete=models.CASCADE,related_name="productor2" ,null=True)
    variedad = models.CharField(max_length=50, null=True)
    calibre = models.CharField(max_length=50, choices = CALIBRE, null=True,default=1)
    cantidad_actual = models.IntegerField(default=0)
    cantidad_necesaria = models.IntegerField(default=0)
    contenido = models.CharField(max_length=50, null=True)
    refrigeracion = models.BooleanField(default=False)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE,related_name='ClienteSoli')
    fecha_creacion = models.DateTimeField(default=timezone.now)
    imagen = models.ImageField(upload_to="Posts", null=True)
    EstadoSolicitud = models.CharField(max_length=50, null=True, choices=EstadoSolicitudCompra, default='3')
    transportista = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name="transportista")
    transporte = models.ForeignKey(Transporte, on_delete=models.CASCADE, null=True,related_name="transporte")
    comentariosTransportista = models.TextField(default="")
    class Meta:
        ordering = ['-fecha_creacion']

class Posthistorico(models.Model):
    
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    idpost= models.ForeignKey(Post,on_delete=models.CASCADE,null=True)
    productoreq = models.CharField(max_length=50,choices=PRODUCTOS, null=True)
    producto = models.ManyToManyField(Producto,related_name="Postproductoh")
    #productor = models.ManyToManyField(User,related_name="productorh" )
    variedad = models.CharField(max_length=50, null=True)
    calibre = models.CharField(max_length=50, choices = CALIBRE, null=True,default=1)
    cantidad_actual = models.IntegerField(default=0,null=True)
    cantidad_necesaria = models.IntegerField(default=0,null=True)
    contenido = models.CharField(max_length=50, null=True)
    refrigeracion = models.BooleanField(default=False,null=True)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE,related_name='ClienteSolih',null=True)
    fecha_creacion = models.DateTimeField(default=timezone.now,null=True)
    fecha_modificacion = models.DateTimeField(null=True)
    imagen = models.ImageField(upload_to="Posts", null=True)
    EstadoSolicitud = models.CharField(max_length=50, null=True, choices=EstadoSolicitudCompra, default='3')
    transportista = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name="transportistah")
    transporte = models.ForeignKey(Transporte, on_delete=models.CASCADE, null=True,related_name="transporteh")
    comentariosTransportista = models.TextField(default="",null=True)   

class Post_productos(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    cantidad_pujada = models.IntegerField(default=0)

class Comprobante(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE,related_name="CompUsuario")
    solicitud = models.ForeignKey(Post, on_delete=models.CASCADE,related_name="CompSolicitud", null=True)
    fecha = models.DateTimeField(default=timezone.now)
    monto = models.IntegerField(default=0)

feriavirtual/feriavirtualapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from requests import post
from .models import *
from django.contrib import admin
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.forms import ModelForm, TextInput, EmailInput
PRODUCTOS =(
    ("1", "Cerezas "),
    ("2", "Uvas"),
    ("3", "Arándanos "),
    ("4", "Nueces"),
    ("5", "Manzana"),
    ("6", "Ciruela"),
    ("7", "Peras"),
    ("9", "Durazno"),
    ("11", "Frutilla"),
    ("12", "Granada"),
    ("13", "Limón"),
    ("14", "Mandarina"),
    ("15", "Naranja"),
    ("16", "Sandia "),
    ("17", "Melón"),
    ("18", "Mora"),
    ("19", "Pera"),
    ("20", "Manzana"),
)
class FormRegistroUsuario(UserCreationForm):

    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirma Contraseña',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','dni','email','password1','password2','rol','direccion','codigopostal']
        help_texts = {k:"" for k in fields}
class FormRegistroInterno(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirma Contraseña',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','dni','email','password1','password2','direccion','codigopostal']
        help_texts = {k:"" for k in fields}
        


class FormPujarSubasta(forms.Form):
    cantidad = forms.IntegerField(help_text="Ingrese la cantidad que desea aportar para satisfacer el pedido.")

class FormProductos(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ('producto','variedad','calibre','cantidad','precio', 'imagen',)
        labels = {
            'cantidad': ('Cantidad en cajas:'),
        }
class FormContratos(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        super(FormContratos, self).__init__(*args, **kwargs)
        self.fields['usuario'].queryset = User.objects.filter(rol="1")  | User.objects.filter(rol="1")
    class Meta:
        model = Contrato
        fields = ('usuario','fecha_inicio','fecha_termino')

class FormVenta(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        super(FormVenta, self).__init__(*args, **kwargs)
        self.fields['cliente'].queryset = User.objects.filter(rol="3")  | User.objects.filter(rol="2")
    class Meta:
        model = Post
        fields = ('cliente','productoreq','variedad','calibre','cantidad_necesaria','refrigeracion','contenido', 'imagen',)
        labels = {
            'cantidad_necesaria': ('Cantidad en cajas:'),
            'imagen': ('Imagen de referencia (opcional)')
        }
    def __init__(self, *args, **kwargs):
        super(FormVenta, self).__init__(*args, **kwargs)
        self.fields['imagen'].required = False
        self.fields['cliente'].queryset = User.objects.filter(rol="3")  | User.objects.filter(rol="2")
        self.fields['productoreq'].choices = PRODUCTOS
class FormVentaCliente(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('productoreq','variedad','calibre','cantidad_necesaria','refrigeracion','contenido', 'imagen',)
        labels = {
            'cantidad_necesaria': ('Cantidad en cajas:'),
            'imagen': ('Imagen de referencia (opcional)'),
            'productoreq': ('Producto requerido')
        }
    def __init__(self, *args, **kwargs):
        super(FormVentaCliente, self).__init__(*args, **kwargs)
        self.fields['imagen'].required = False



class FormSolicitudEstadoTransportista(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("11", "En camino"),
                ("12", "Viaje interrumpido"),
                ("13", "Destino"),
            ]
    class Meta:
        model = Post
        fields = ('EstadoSolicitud',)
class FormSolicitudEstadoRevisor(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("9", "Rechazar"),
                ("10", "Aprobar"),
            ]
    class Meta:
        model = Post
        fields = ('EstadoSolicitud',)
class FormSolicitudEstadoProductor(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("6", "Entregado en bodega"),
                ("7", "Viaje Interrumpido")

            ]
    class Meta:
        model = Post
        fields = ('EstadoSolicitud',)    
class FormSolicitudClienteExterno(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("14", "Pagar"),
                ("15", "Rechazar pedido"),

            ]
    class Meta:
        model = Post
        fields = ('EstadoSolicitud',)    
class FormSolicitudEstado(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("1", "Aprobado"),
                ("2", "Rechazado"),
                ("3", "Pendiente")
            ]
    class Meta:
        model =  Post
        fields = ('EstadoSolicitud',)



class FormRegistrarTransporte(forms.ModelForm):
    class Meta:
        model = Transporte
        fields = ('tamaño','refrigeracion','tarifa',)
        
        
class FormEstadoSolicitud(forms.ModelForm):
    class Meta:
        model = Post
        fields = ( 'EstadoSolicitud',)
        labels = {
            'EstadoSolicitud': ('Selecciones el estado :'),
        }

feriavirtual/feriavirtualapp/templates/Solicitud.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">
    
    <form class="form rounded "  style="background-color:#ffffffc1" method="POST" enctype="multipart/form-data">
        <h1>Inicia venta</h1>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class=" rounded "  style="background-color:#22d14edb" name="register">
    </form>
</div>


{% endblock %}

feriavirtual/feriavirtualapp/templates/SolicitudClientes.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">
    
    
    <form class="form rounded "  style="background-color:#ffffffc1" method="POST" enctype="multipart/form-data">
        <h1>Inicia una venta</h1>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class=" rounded "  style="background-color:#22d14edb" name="register">
    </form>
</div>


{% endblock %}

feriavirtual/feriavirtualapp/templates/Venta-local.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}
{% if request.user.rol == "3"  %} 
    <body>

        <!-- Header-->

        <!-- Section-->
        


        <a  class="" href="/carrito.html" style=" right: 20px; position: absolute; margin-top: 10px; "    >
            <img src="https://cdn-icons-png.flaticon.com/512/5087/5087847.png" alt="" width="30" height="30">
            {% if request.session.cart.items %}
            {% for key, value in request.session.cart.items %}
                 <tr class="text-center">                     
                     {{ value.quantity }}                             
                 </tr>
            {% endfor %}
            {% endif %}
        
        
        </a>
        
        


        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5  row-cols-xs-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Venta local</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.imagen.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.get_producto_display}}</h5>
                                    <h6 class="fw-bolder">{{product.variedad}}</h6>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">$ {{product.precio}}</span>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                {% if user.is_authenticated %}
                                <button class="btn">
                                    <a href="{% url 'add_product_catalogo' product.id %}"><span>Añadir a carrito</span></a>
                                </button>
                                {% endif %}
                                {% if user.is_anonymous %}
                                
                                    <a href=""><span></span></a>
                                    <button class="btn">
                                        <a href="login"><span>comprar</span></a>
                                    </button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

        <!-- Footer-->

    </body>
    {% endif  %} 
{% endblock %}

feriavirtual/feriavirtualapp/templates/seguimientoLista.html
{% extends 'baseboostrap.html' %}
{% load humanize %}

{% block content %}

{% if request.user.rol == "4" or request.user.rol == "7"  %}


{% else %}
<br>
<br>
<div class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table
          id="zero_config"
          class="table table-striped table-bordered">
         
          <thead>
            <tr>
              <th>Numero de seguimiento</th>
              <th>Estado</th>
              <th>Fecha de creacion</th>
              <th>Seguimiento</th>
            </tr>
          </thead>
          <tbody>
            {% for s in solis  %}
            <tr>
                <td>{{ s.id }}</td>
                <td>{{ s.get_EstadoSolicitud_display }}</td>
                <td>{{ s.fecha_creacion|date:"d/m/Y" }}</td>
                <td><p class="boton_mod rounded "><a  href="{% url 'seguimiento' s.pk%}"><iconify-icon icon="ic:baseline-search"></iconify-icon></a></p></td>

            </tr>
        {% endfor %}
          </tbody>

        </table>


      </div>
    </div>
  </div>
  {%endif%}


{% endblock %}

feriavirtual/feriavirtualapp/templates/solicitudesClienteExterno.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">
  <DIv>DESLIZAR</DIv>
    <i class="fa-sharp fa-solid fa-arrow-left" style="float:left;"></i>
    <i class="fa-sharp fa-solid fa-left-right"></i>
    <i class="fa-sharp fa-solid fa-arrow-right" style="float:right;"></i>
    
  <div class="table-responsive">
    <table class="table table-light table-striped">
      <tr class="table-active">
      
          <td><b>Usuario </b></td>
          <td><b>Producto</b></td>
          <td><b>Variedad</b></td>
          <td><b>Calibre</b></td>
          <td><b>Cantidad_actual</b></td>
          <td><b>Cantidad_necesaria</b></td>
          <td><b>Contenido</b></td>
          <td><b>Cliente</b></td>
          <td><b>Fecha_creacion</b></td>
          <td><b>Direccion</b></td>
          <td><b>Codigo Postal</b></td>
          <td><b>Estado Solicitud Compra</b></td>
          <td><b>Imagen</b></td>
          <td><b>ModEstado</b></td>

        {% for s in soli %} 
        <tr>
      
            <td>{{ s.usuario.username }}</td>
        
            <td>{{ s.get_producto_display }}</td>
    
            <td>{{ s.variedad }}</td>
            
            <td>{{ s.get_calibre_display }}</td>
  
            <td>{{ s.cantidad_actual }}</td>

            <td>{{ s.cantidad_necesaria }}</td>

            <td>{{ s.contenido }}</td>

            <td>{{ s.cliente }}</td>

            <td>{{ s.fecha_creacion|date:"d/m/Y" }}</td>

            <td>{{ s.usuario.direccion }}</td>

            <td>{{ s.usuario.codigopostal }}</td>

            <td>{{ s.get_EstadoSolicitud_display }}</td>
            {% if person.image %}
            <td> <img style="height: 100px;"  src="{{ s.imagen.url }}"> </td>
            {% else %}
            <td><b></b></td>
            {% endif %}
            {% if s.EstadoSolicitud == "13"%}
            <td><p class="boton_mod"><a  href="{% url 'modificarSolicitudClienteExterno' s.pk%}"  style="background-color:#71da8cdb; color: black;">Pagar o rechazar</a></p></td>
            {% endif %}

          
        
          </tr>
        {% endfor %}
      </table>
    </div>


</div>



  


{% endblock %}

feriavirtual/feriavirtualapp/templates/solicitudesProductor.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<br>
<iconify-icon icon="ic:round-rotate-90-degrees-ccw"></iconify-icon>
  <div>Voltear si es necesario  </div>

<div class="main">
  <DIv>DESLIZAR</DIv>
    <i class="fa-sharp fa-solid fa-arrow-left" style="float:left;"></i>
    <i class="fa-sharp fa-solid fa-left-right"></i>
    <i class="fa-sharp fa-solid fa-arrow-right" style="float:right;"></i>


<div class="card">
  <div class="card-body">

  <div class="table-responsive">
    <table class="table table-light table-striped">
      <tr class="table-active">
      
          <td><b>Usuario </b></td>
          <td><b>Producto</b></td>
          <td><b>Variedad</b></td>
          <td><b>Calibre</b></td>
          <td><b>Cant Actual</b></td>
          <td><b>Cant Necesaria</b></td>
          <td><b>Contenido</b></td>
          <td><b>Cliente</b></td>
          <td><b>Fecha Inicio</b></td>
          <td><b>Destino</b></td>
          <td><b>Codigo Postal</b></td>
          <td><b>Estado Producto</b></td>
          <td><b>Imagen</b></td>
          <td><b>Notificar entrega</b></td>

        {% for s in solip %} 
        <tr>
            
            <td>{{ s.usuario.username }}</td>
        
            <td>{{ s.get_producto_display }}</td>
    
            <td>{{ s.variedad }}</td>
            
            <td>{{ s.get_calibre_display }}</td>
  
            <td>{{ s.cantidad_actual }}</td>

            <td>{{ s.cantidad_necesaria }}</td>

            <td>{{ s.contenido }}</td>

            <td>{{ s.cliente }}</td>

            <td>{{ s.fecha_creacion|date:"d/m/Y" }}</td>

            <td>{{ s.usuario.direccion }}</td>

            <td>{{ s.usuario.codigopostal }}</td>

            <td>{{ s.get_EstadoSolicitud_display }}</td>

            {% if s.imagen %}
            <td> <img style="height: 100px;"  src="{{ s.imagen.url }}"> </td>
            
            {% else %}
            <td><b></b></td>
            {% endif %}
            <td><p class="boton_mod"><a  href="{% url 'modificarsolicitudProductor' s.pk%}"  ><iconify-icon icon="ic:outline-system-update-alt"></iconify-icon></a></p></td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
</div>



  


{% endblock %}